### ISSUE TITLE
Allow for alternative output stream, suchas simple stdout

### ISSUE THREAD

**Issue by yarikoptic** [pyout/pyout#73]
NB I feel like we have discussed something like that already but do not see any related open issue

ATM there seems to be no way to instruct pyout's Tabular to work with a simple serial stream to output to, such as `sys.stdout`. Not even sure yet how to test (besides smoke testing) output produced by pyout in applications using it (such as datalad).

Obviously in such cases pyout should not attempt to do any fancy repaint of previous records but could have a variety of modes, which actually could be used by the current Tabular as well

- wait until all records are complete, figure out needed widths and output at once
- output as soon as it knows everything for the next record (while Threads still used in parallel to run callbacks), but possibly disregarding possible future formatting width change(s)
- output records multiple times, so that an updated record is output whenever any of its callbacks completed.    

Probably (most) useful only whenever some alternative output serialization (e.g. simple dict/json records outputs) with some additional field to signal either record is complete.

**Comment by kyleam** [comment]
> ATM there seems to be no way to instruct pyout's Tabular to work with a simple serial stream to output to, such as `sys.stdout`.

Before 681b475a (RF: Remove unneeded parameters from Tabular, 2018-11-16), Tabular had a `stream` parameter, but that and `force_styling` were removed with the following motivation: "The Tabular class is the user-facing interface.  There's no reason to expose these internal knobs that are used solely for testing."  I still agree with that motivation, and ...

> Not even sure yet how to test (besides smoke testing) output produced by pyout in applications using it (such as datalad).

I suppose adding them back doesn't really help out applications using pyout because they'd still have to mock something somewhere in the chain.

Anyway, I agree that we should make it more convenient for applications that test the output, and I think a good way to go about that is defining alternative `interface.Stream` objects that can subbed in and provide more convenient inspection of data.
